SimonBoothroyd/descent

.github/workflows/lint.yaml
descent/metrics.py
descent/objectives/energy.py
descent/tests/mocking/systems.py
descent/tests/objectives/test_energy.py
examples/energy-and-gradient.ipynb
integration-tests/test_energy_training.py

This PR adds a set of very simple integration tests that ensure that the energy objective contribution can
i) be used in a toy parameter optimisation when both energies and gradients are being used as reference data
ii) the optimised parameters match expected values based on contrived initial perturbations.
The PR also updates the example as that also acts as a nice smoke test that at the very least the objective can be decreased.

Add simple integration tests and update example

---

descent/models/__init__.py
descent/models/models.py
descent/models/smirnoff.py
descent/objectives/energy.py
descent/objectives/objectives.py
descent/tests/models/test_smirnoff.py
descent/tests/objectives/test_energy.py
descent/tests/objectives/test_objectives.py
examples/energy-and-gradient.ipynb
integration-tests/test_energy_training.py

This PR abstracts the code to no longer expect `smirnoffee` type parameter perturbation tensors and id lists, but rather a `torch.nn.Module` that should take as input some information about a molecule (whether that be a DGL graph or a vectorised system) and output an 'up to date' vectorized representation of the system.
This abstraction should a) make integration with things like PyTorch Lightning easier and b) make it so that NN models like those built with `espaloma` can make use of the objectives defined here.

Abstract parameter perturbation into NN module

---

descent/models/smirnoff.py
descent/objectives/energy.py
descent/tests/models/test_smirnoff.py

This PR adds a new `covariance_tensor` argument to the SMIRNOFF model that allows users to apply a transform to the 'parameter delta' before it is applied to a parameterised system. This allows parameters to easily be scaled or be made linear combinations of one another much like `forcebalance`'s mathematical vs physical parameters and parameter eval statements.

Add support for SMIRNOFF covariance tensor

---

descent/objectives/energy.py
descent/tests/objectives/test_energy.py
devtools/conda-envs/meta.yaml

This PR ensures that molecules that have conformers that map to different internal coordinates e.g. one conformer has a planar N and another a pyramidal N, are correctly handled by padding the B and G matrices with zeros so they can be batched together.

Support molecules with conformers with different ICs

---

descent/tests/utilities/test_smirnoff.py
descent/tests/utilities/test_utilities.py
descent/utilities/__init__.py
descent/utilities/smirnoff.py
descent/utilities/utilities.py
examples/energy-and-gradient.ipynb
setup.cfg

This PR adds a new `descent.utilities.smirnoff.exercised_parameters` utility that will return the keys of the SMIRNOFF parameters exercised by a given dataset. The utility also allows users to easily filter by handler (e.g. only return back exercised bond parameters) or attribute (e.g. only return force constants).

Add utility to find SMIRNOFF parameters exercised by dataset

---

descent/optim/__init__.py
descent/optim/_lm.py
descent/tests/optim/test_lm.py

This PR adds support for  hessian diagonal search (i.e. when `trust0 < 0.0` in ForceBalance) to the Levenberg-Marquardt optimizer.

Add hessian diagonal search support to LM optimizer

---

descent/optim/_lm.py
descent/tests/optim/test_lm.py

This PR adds convergence criteria to the LM optimizer.

Add LM optimizer convergence checks

---

descent/optim/_lm.py
descent/tests/utils/test_loss.py
descent/utils/loss.py

This PR adds a `to_closure` utility function that converts a loss function with an analytically computable hessian to a 'closure' function that can be passed to, e.g., the LM optimizer

Add `to_closure` utility

---

descent/targets/dimers.py
descent/tests/utils/test_molecule.py
descent/utils/molecule.py

This PR splits out the `mol_to_smiles` from the `dimers` target into a more general utility.

Split `mol_to_smiles` into a util

---

descent/targets/thermo.py
descent/tests/utils/test_loss.py
descent/utils/loss.py

This PR adds a utility to compute the approximate hessian using the outer product approximation. This is useful, for e.g., when optimizing physical properties whose hessian cannot yet be analytically computed.

Add approximate hessian utility

---

descent/targets/thermo.py
descent/tests/targets/test_thermo.py

This PR updates after up-stream syntax changes.

Update `thermo` target to use new `smee` syntax

---

descent/optim/_lm.py
descent/tests/optim/test_lm.py

This PR updates the LM optimiser to return the parameters with the lowest loss, rather than the parameters of the final step.

Return parameters with lowest loss from LM optimizer

---

descent/targets/dimers.py
descent/targets/thermo.py
descent/tests/targets/test_dimers.py
descent/tests/targets/test_thermo.py
descent/tests/utils/test_dataset.py
descent/utils/dataset.py
devtools/envs/base.yaml

This PR migrates from using raw Arrow tables to instead using Hugging Face datasets. These use Arrow tables under the hood so we get the same benefits, but also have a bunch of rich convenience helpers on top.

Migrate to Hugging Face datasets

---

descent/tests/utils/test_reporting.py
descent/utils/reporting.py

This PR adds a number of helpers to print the current values in a force field to the terminal.

Add utils to print SMEE force field parameters

---

descent/targets/thermo.py
descent/tests/targets/test_thermo.py
devtools/envs/base.yaml

This PR updates the `thermo` target to also return std dev. values.

Add uncertainties to thermo target

---

descent/optim/_lm.py
descent/targets/dimers.py
descent/targets/energy.py
descent/targets/thermo.py
descent/tests/targets/test_thermo.py
descent/utils/dataset.py
descent/utils/loss.py
descent/utils/reporting.py

This PR ensures that SMILES patterns in thermo datasets are matched, aligning them with other targets.

Ensure thermo dataset SMILES are mapped

---

.pre-commit-config.yaml
Makefile
descent/targets/dimers.py
descent/targets/thermo.py
descent/tests/optim/test_lm.py
descent/tests/utils/test_loss.py
descent/utils/dataset.py
descent/utils/loss.py
descent/utils/reporting.py
devtools/envs/base.yaml
pyproject.toml

This PR swaps to `ruff` as the main formatter / linter.

Reformat with `ruff`

---

descent/tests/test_train.py
descent/train.py

This PR adds a set of convenience tools / classes to mimic the kind of convenient API that forcebalance exposes via the new `Trainable` class.
The `Trainable` class takes configuration for parameters and attributes:
```python
parameter_config = {
"vdW": ParameterConfig(
cols=["epsilon", "sigma"],
scales={"epsilon": 10.0, "sigma": 1.0},
limits={"epsilon": (0.0, None), "sigma": (0.0, None)},
include=[mock_ff.potentials_by_type["vdW"].parameter_keys[0]],
),
"Bonds": ParameterConfig(
cols=["length"],
scales={"length": 1.0},
limits={"length": (0.1, 0.7)},
exclude=[mock_ff.potentials_by_type["Bonds"].parameter_keys[0]],
),
}
attribute_config = {
"vdW": AttributeConfig(
cols=["scale_14"],
scales={"scale_14": 0.1},
limits={"scale_14": (0.0, None)},
)
}
```
Once created,
```
trainable = …
```

Add train utilities

---

devtools/envs/base.yaml
mkdocs.yml

There was an API change in MkDocs which breaks the Jupyter plugin. It doesn't get used in this repo so it is removed here.

Fix docs builds

---

descent/targets/dimers.py
descent/tests/targets/test_dimers.py

This PR extends the dimer report function to accept different topologies for each force field allowing the comparison of force fields with different SMARTS patterns or types of parameters such as v-sites.

Allow different topologies for each force field

---

descent/targets/energy.py
descent/tests/targets/test_energy.py

This PR fixes a typo where the gradient, rather than force was returned for the energy target

Fix incorrect force sign in energy target

---

.github/workflows/ci.yaml
Makefile
descent/train.py
devtools/envs/base.yaml

This PR adds backwards compatibility for `pydantic =1`.

Add `pydantic =1` support

---

descent/targets/energy.py
descent/tests/targets/test_energy.py

Update the energy and force predictions to be on the same device as the reference values to allow training on the GPU

Enable Energy and Force fitting on a GPU
